RARITIES = ["S", "A", "B", "C", "D", "E", "F"]

RARITY_BOUNDS = {
    "S": (80, 150),
    "A": (65, 79),
    "B": (50, 64),
    "C": (40, 49),
    "D": (30, 39),
    "E": (20, 29),
    "F": (0, 19),
}

SURFACE_MAP = {
    "00": "Dry",
    "01": "Wet",
    "10": "Dirt",
    "11": "Dirt Wet",
    "20": "Gravel",
    "30": "Ice",
    "40": "Aspht Dirt",
    "41": "Aspht Dirt Wet",
    "50": "Sand",
    "51": "Sand Wet",
    "60": "Snow",
    "70": "Grass",
    "71": "Grass Wet",
    "b0": "Aspht Gravel",
    "c0": "Aspht Sand",
    "c1": "Aspht Sand Wet",
    "d0": "Aspht Snow",
    "e0": "Sand Dirt",
    "f0": "Aspht Grass Dirt",
    "g0": "Ice Snow",
    "h1": "Snow Dirt Wet",
    "i0": "Aspht",
    "k0": "Dirt",
    "m0": "Aspht Dirt",
    "A1": "D Aspht Wet",
    "B1": "D Wet Aspht",
    "C0": "D Aspht Sand",
    "D0": "D Aspht Snow",
    "E0": "D Aspht Dirt",
}
